name: Fix React version

on:
  workflow_dispatch:

jobs:
  fix-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Downgrade React
        run: yarn add react@18.2.0 react-dom@18.2.0

      - name: Create/Update fix-react branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -B fix-react
          git add package.json yarn.lock
          git commit -m "Fix React version to 18.2.0" || echo "No changes to commit"
          git push origin fix-react --force
