name: Fix React + Build & Push Docker

on:
  workflow_dispatch:
    inputs:
      react_version:
        description: 'React version to upgrade'
        required: true
        default: '18.2.0'

env:
  REACT_VERSION: ${{ github.event.inputs.react_version }}
  IMAGE_NAME: ghcr.io/${{ github.repository }}/notionnext

jobs:
  fix-react-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      # 3. Upgrade React & React-DOM
      - name: Upgrade React
        run: |
          echo "Upgrading React to $REACT_VERSION"
          yarn add react@$REACT_VERSION react-dom@$REACT_VERSION

      # 4. Install dependencies
      - name: Install dependencies
        run: yarn install

      # 5. Build Next.js
      - name: Build project
        run: yarn build

      # 6. Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # 8. Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
