name: Fix React + Build Docker + Push GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fix-react-build-docker:
    runs-on: ubuntu-latest

    env:
      REACT_VERSION: "18.2.0"      # 想要升级/降级的 React 版本
      IMAGE_NAME: ghcr.io/${{ github.repository }}/notionnext:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Upgrade React version
        run: |
          echo "Upgrading React to $REACT_VERSION"
          yarn add react@$REACT_VERSION react-dom@$REACT_VERSION

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Next.js project
        run: yarn build

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image to GHCR
        run: |
          docker push $IMAGE_NAME
