name: Fix React version

on:
  workflow_dispatch: # 手动触发

jobs:
  fix-react:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 必须 fetch 所有分支

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # 3. 安装依赖
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4. 修改 React 版本
      - name: Downgrade React
        run: yarn add react@18.2.0 react-dom@18.2.0

      # 5. 自动创建/更新 fix-react 分支
      - name: Push changes to fix-react
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git branch -f fix-react
          git add package.json yarn.lock
          git commit -m "Fix React version to 18.2.0" || echo "No changes to commit"
          git push origin fix-react --force
